# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('page_type', models.CharField(choices=[('trending', 'Trending'), ('repo', 'Repository')], max_length=10)),
                ('page', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingCrawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, null=True)),
                ('since', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('readme', models.FileField(null=True, upload_to='')),
                ('star', models.IntegerField()),
                ('fork', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
