# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingcrawler',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trendingcrawler',
            name='since',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trendingrepository',
            name='fork',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trendingrepository',
            name='readme',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trendingrepository',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
